# Generated by Django 5.2.15 on 2026-06-13 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_query", models.TextField()),
                ("recommendation_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FitnessGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("loss", "Weight Loss"),
                            ("gain", "Muscle Gain"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="maintenance",
                        max_length=15,
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                (
                    "target_weight",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                ("daily_calorie_goal", models.PositiveIntegerField(default=2000)),
                ("daily_protein_goal", models.PositiveIntegerField(default=120)),
                ("daily_carbs_goal", models.PositiveIntegerField(default=230)),
                ("daily_fats_goal", models.PositiveIntegerField(default=65)),
                ("daily_water_goal", models.PositiveIntegerField(default=2500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("calories", models.DecimalField(decimal_places=2, max_digits=6)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carbs", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=6)),
                ("serving_size", models.CharField(default="100g", max_length=100)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorite_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=200)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
                ),
                ("calories", models.DecimalField(decimal_places=2, max_digits=6)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carbs", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=6)),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "food_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="tracker.fooditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "logged_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "unique_together": {("user", "logged_at")},
            },
        ),
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "logged_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "unique_together": {("user", "logged_at")},
            },
        ),
    ]
