# Generated by Django 5.2.15 on 2026-06-16 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_dailyroutine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDietCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "logged_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("is_eaten", models.BooleanField(default=False)),
                (
                    "linked_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diet_checks",
                        to="tracker.foodlog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["logged_at", "meal_type"],
                "unique_together": {("user", "meal_type", "logged_at")},
            },
        ),
        migrations.CreateModel(
            name="DietMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=15,
                    ),
                ),
                ("items", models.TextField(help_text="Checklist items text list")),
                (
                    "calories",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "protein",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "carbs",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "fat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "meal_type")},
            },
        ),
    ]
